# Generated by Django 3.2 on 2021-04-11 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(max_length=6)),
                ('nombre_ciudad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Productores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(max_length=2)),
                ('cedula', models.CharField(max_length=20)),
                ('nombre1', models.CharField(max_length=20)),
                ('nombre2', models.CharField(max_length=20)),
                ('apellido1', models.CharField(max_length=20)),
                ('apellido2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tiposlabores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tiposproductoscontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(max_length=30)),
                ('periodo_carencia', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_ua', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Viveros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=20)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Productoscontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ica', models.CharField(max_length=10)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('frecuencia_aplicacion', models.CharField(max_length=10)),
                ('valor_producto', models.CharField(max_length=10)),
                ('tipos_productos_control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.tiposproductoscontrol')),
            ],
        ),
        migrations.CreateModel(
            name='Productores_viveros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.productores')),
                ('viveros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.viveros')),
            ],
        ),
        migrations.CreateModel(
            name='Labores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_labor', models.DateTimeField()),
                ('descripcion_labor', models.CharField(max_length=255)),
                ('productos_control', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.productoscontrol')),
                ('tipo_labores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.tiposlabores')),
            ],
        ),
    ]
