# Generated by Django 3.1.7 on 2021-04-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(max_length=6)),
                ('nombre_ciudad', models.CharField(max_length=255)),
            ],
        ),
    ]
