# Generated by Django 3.1.7 on 2021-04-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labores',
            name='productos_control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.productoscontrol'),
        ),
        migrations.AlterField(
            model_name='labores',
            name='tipo_labores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.tiposlabores'),
        ),
    ]
