# Generated by Django 3.1.7 on 2021-04-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210411_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productores',
            name='apellido2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productores',
            name='nombre2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
