# Generated by Django 3.2 on 2021-04-10 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_productores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viveros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=20)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Productores_viveros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.productores')),
                ('viveros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.viveros')),
            ],
        ),
    ]
