# Generated by Django 3.1.7 on 2021-04-11 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210411_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoscontrol',
            name='frecuencia_aplicacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productoscontrol',
            name='tipos_productos_control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.tiposproductoscontrol'),
        ),
        migrations.AlterField(
            model_name='productoscontrol',
            name='valor_producto',
            field=models.IntegerField(),
        ),
    ]
