# Generated by Django 3.1.7 on 2021-04-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210411_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudades',
            name='codigo_dane',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='productoscontrol',
            name='registro_ica',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='viveros',
            name='codigo',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
