# Generated by Django 3.1.7 on 2021-04-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210411_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productores_viveros',
            name='productores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.productores', unique=True),
        ),
        migrations.AlterField(
            model_name='productores_viveros',
            name='viveros',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.viveros', unique=True),
        ),
        migrations.AlterField(
            model_name='productoscontrol',
            name='tipos_productos_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.tiposproductoscontrol'),
        ),
        migrations.AlterField(
            model_name='productoscontrol',
            name='valor_producto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tiposproductoscontrol',
            name='periodo_carencia',
            field=models.IntegerField(),
        ),
    ]
